### ISSUE TITLE
Prod - Unable to obtain DB connection from pool

### ISSUE THREAD

**Issue by lgarofalo** [ShelterTechSF/askdarcel-api#182]
Solved by starting a new container, requires research.

Likely related to event with higher volume of users than previous.

`Jul 15 00:09:14 434d059913b3 appserver: 2017-07-15 21:20:52 +0000: Rack app error handling request { GET /categories }
Jul 15 00:09:14 434d059913b3 appserver: #<ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 8.352 seconds); all pooled connections were in use>
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in `block in wait_poll'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `loop'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `wait_poll'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:154:in `internal_poll'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:278:in `internal_poll'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `block in poll'
Jul 15 00:09:14 434d059913b3 appserver: /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:158:in `synchronize'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in `poll'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:709:in `acquire_connection'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:501:in `checkout'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:875:in `retrieve_connection'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_handling.rb:91:in `connection'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/query_cache.rb:47:in `block in install_executor_hooks'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:396:in `instance_exec'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:396:in `block in make_lambda'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:546:in `catch'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:546:in `block in default_terminator'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:170:in `block in halting'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `block in call'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `each'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `call'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_complete_callbacks'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:107:in `complete!'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:64:in `ensure in block in run!'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:64:in `block in run!'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:58:in `tap'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:58:in `run!'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/executor.rb:10:in `call'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/static.rb:136:in `call'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:522:in `call'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
Jul 15 00:09:14 434d059913b3 appserver: /home/app/webapp/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'`

**Comment by lgarofalo** [comment]
Hasn't happened again, closing.
